project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "JedR Academy"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Overview"
        url: index.qmd
      - text: "Trainings"
        url: resources/training.qmd
      - text: "Trials"
        url: resources/trials.qmd
      - text: "JedR Contribution"
        url: resources/github.qmd
        
          

format:
  html:
    theme: cosmo
    toc: true