---
title: "JedR Trial: Plot"
engine: knitr
format: live-html
webr:
  packages:
    - tidyverse
    - dplyr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}} 
{{< include ./_extensions/r-wasm/live/_gradethis.qmd >}}

## JedR Trial No. 4: Plotting

In this JedR Trial, we'll be exploring the [ggplot2](https://ggplot2.tidyverse.org/) skills. Like our previous exercise, we'll be using the data `starwars` in the `tidyverse` packages.

Your humanoid robot editor (J-327D) has asked to _**see**_ how many characters there are for each species in the `starwars` data. They have asked you to make a bar chart from this data.

As you may recall in your training, making a chart usually takes two steps: Preparing the data, then plotting the data.

As a reminder, here is the `starwars` data:

```{r glimpse}
#| message: false
library(tidyverse)

glimpse(starwars)
```

### Prepare your data

To prepare this data for your plot, you need to:

1. Group by species and count the number of rows. Name the new variable `characters`
1. Arrange the result so the most characters are at the top.
1. Drop any NA values.
1. Save the result of this into a new data frame called `species_count` and then print that out at the end.

```{webr}
#| exercise: ex_1
starwars |>
  ______
```

::: {.solution exercise="ex_1"}
#### Solution

```{webr}
#| exercise: ex_1
#| solution: true
species_count <- starwars |>
  group_by(species) |>
  summarize(characters = n()) |>
  arrange(desc(characters)) |>
  drop_na()

species_count
```

```{webr}
#| exercise: ex_1
#| check: true

grade_this({
if (identical(.result, .solution)) {
  pass(message = "Wow! The force is with you!")
} else {
  fail(message = "The wrong answer it is, young Padawan.")
}})

```
:::

::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 1

# Fill in the blanks with functions and variables

``` r
# fill in the blanks with functions and variables

species_count <- starwars |>
  ________(_______) |>
  _________(characters = _()) |>
  _______(desc(characters)) |>
  drop_na()

species_count
```
:::
:::

### Plotting the chart

Now that we have our prepared data into `species_count`, you need to plot your data as a bar chart, with the species with the most characters at the top.

A couple of things that the code checker is persnickety about:

- You should use the geom for a column chart, but the flip it so you can read the species names.
- Don't forget to reorder your bars.
- For the labs, we're looking only for three things:
  - The title should be "Count of species in Star Wars"
  - The axis that has the numbers should be called "Number of characters".
  - The other axis label should be blank or removed.
  
```{webr, include=FALSE}
#| exercise: ex_2
#| setup: true

library(tidyverse)

species_count <- starwars |>
  group_by(species) |>
  summarize(characters = n()) |>
  arrange(desc(characters)) |>
  drop_na()
```

```{webr}
#| exercise: ex_2
species_count
```

::: {.solution exercise="ex_2"}
#### Solution

```{webr}
#| exercise: ex_2
#| solution: true
ggplot(species_count, aes(x = reorder(species, characters), y = characters)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Count of species in Star Wars",
    y = "Number of characters",
    x = ""
  )
```

```{webr}
#| exercise: ex_2
#| check: true

grade_this({
if (identical(.result, .solution)) {
  pass(message = "Wow! The force is with you!")
} else {
  fail(message = "The wrong answer it is, young Padawan.")
}})

```
:::

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 1

# Try building the plot one layer at a time
# First, just get the chart to work

```r
ggplot(species_count, ___(x = _______, y = __________)) +
  geom_col()
```

:::
:::

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 2

# Then you modify to reorder the bars and flip the coordinates
```r
ggplot(species_count, ___(x = _______(species, characters), y = __________)) +
  geom_col() +
  __________()
```
:::
:::

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 3

# Then add your labels

```r
ggplot(species_count, ___(x = _______(species, characters), y = __________)) +
  geom_col() +
  __________() +
  ____(
    _____ = "Count of species in Star Wars",
    y = "Number of characters",
    x = ""
  )
```
:::
:::

Show your completed plot to your JedR Master.
