---
title: "JedR Trial: Count"
engine: knitr
format: live-html
webr:
  packages:
    - tidyverse
    - dplyr
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ./_extensions/r-wasm/live/_gradethis.qmd >}}

## JedR Trial No. 2: Summarize by counting

As a **JedR Padawan** of the *Galactic News Hub*, you have been assigned to help with a new story about the demographics of the Star Wars Universe. After pitching a few different topics, your droid editor (J-327D) has green lighted a pitch about species variation. For this article, you have been asked to provide a summary statistic about which species is the most common in the Star Wars universe.

For this task, you will **summarize** and **group** the characters by species. You will then **arrange** the data to identify the most common species of all the Star Wars characters.

### 1. Summarizing

If you recall from our earlier exercise, `starwars` is a dataset with 87 Star Wars characters.

```{r glimpse, echo: false}
#| message: false
library(tidyverse)

glimpse(starwars)
```

First, we'll need to *group* the data by species and then *summarize* by counting the *n*umber of rows of each species. (We will tackle the arranging part later.)

How do we do that? What functions would we use? *We insist you name the new variable "characters"!*

```{webr}
#| exercise: ex_1
starwars |>
  ______
```

::: {.solution exercise="ex_1"}

#### Solution

```{webr}
#| exercise: ex_1
#| solution: true
starwars |>
  group_by(species) |>
  summarize(characters = n())
```

```{webr}
#| exercise: ex_1
#| check: true

grade_this({
if (identical(.result, .solution)) {
  pass(message = "Wow! The force is with you!")
} else {
  fail(message = "The wrong answer it is, young Padawan.")
}})

```
:::

::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 1

heck out the `group_by()` and `summarize()` in [Chapter 4](https://utdata.github.io/rwdir/count-analysis.html#summarize)

:::
:::

### 2. Arrange the results

While the `group_by()` and `summarize()` functions are great for summarizing this information, a [Padawan youngling](https://www.starwars.com/news/what-is-a-padawan) has pointed out that the information is not ordered. 

🙄 Rolling your eyes, you tell them that you know this! We just need to use another function in order to **arrange** this data. To illustrate your point, let's **arrange** this data now.

As a tip, don't forget that we often want to sort the information by **desc**ending order, because journalists are typically interested in the *most* of something.

```{webr}
#| exercise: ex_2
starwars |>
  group_by(species) |>
  summarize(characters = n())
```

::: {.solution exercise="ex_2"}

#### Solution

```{webr}
#| exercise: ex_2
#| solution: true
starwars |>
  group_by(species) |>
  summarize(characters = n()) |>
  arrange(characters |> desc())
```

```{webr}
#| exercise: ex_2
#| check: true

grade_this({
if (identical(.result, .solution)) {
  pass(message = "Wow! The force is with you!")
} else {
  fail(message = "The wrong answer it is, young Padawan.")
}})

```
:::

::: {.hint exercise="ex_3"}
::: {.callout-note collapse="false"}
## Hint 1

heck out `arrange`. You can [learn more here](https://dplyr.tidyverse.org/reference/arrange.html). 

:::
:::

Now that you've **grouped** the data, **summarized** the number of characters of each species, and **arranged** the data (in **desc**ending order), you can finally tell your editor that you've compiled this information!

What species is the most common in Star Wars?

```{webr}
#| exercise: ex_3
______
```

::: {.solution exercise="ex_3"}

#### Solution

```{webr}
#| exercise: ex_3
#| solution: true
"Human"
```

```{webr}
#| exercise: ex_3
#| check: true

grade_this({
if (identical(.result, .solution)) {
  pass(message = "Wow! The force is with you!")
} else {
  fail(message = "The wrong answer it is, young Padawan.")
}})

```
:::

Excellent! Please tell your JedR Master that you have completed this trial.