---
title: "JedR Trials"
format: html
---

These modules are designed to test and strengthen your R skills through a series of interactive lessons. Each module introduces essential data manipulation and visualization techniques, using engaging exercises based on the `starwars` dataset. If you'd like to run them locally, you can find the necessary files in the `webr-trials/` folder. The topics covered are tailored to the Reporting with Data class and apply in various projects. If you're interested in creating additional JedR Trials content, please explore the contributions tab for guidelines and opportunities to join the JedR Republic.


- [Introduction](/webr-trials/jedr-trial-01-intro.html):
  Introduces the `starwars` data and the interactive format of the
  lessons. Covers some basic functions to look at data.
- [Summarize with Count](/webr-trials/jedr-trial-02-count.html): Covers
  counting rows using group_by and summarize. (We skip `count()` here to
  focus on group_by, summarize and arrange.)
- [Summarize with Math](/webr-trials/jedr-trial-03-sum.html):
  Covers grouping data and math functions within summarize.
- [Plotting](/webr-trials/jedr-trial-04-plot.html): Making a
  very basic ggplot chart.
- [Pivoting](/webr-trials/jedr-trial-05-pivot.html): Making
  data wider and longer.
- [Bind and Join](/webr-trials/jedr-trial-06-bind.html):
  Combining data.
