---
title: "JedR Trial: Plot"
engine: knitr
format: live-html
webr:
  packages:
    - tidyverse
    - dplyr
    - ggplot2
    
render-df: paged-table
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}} 

```{webr}
#| include: FALSE
praise_list <- c("Great job you have done!", "Nice work. You have controlled your fear.", "Wow! The force is with you!", "Great job! Mind tricks don't work on you!", "The Force is strong with you!", "You’ve mastered this task like a true Jedi Knight.", "Your skills rival those of a seasoned Jedi Master.", "The galaxy is lucky to have someone as strong and brave as you.", "The Rebellion couldn’t ask for a better ally.", "You’re the hope the galaxy needs!", "Not even the Death Star could stand in your way.", "Darth Vader would tremble in your presence!", "Even a bounty hunter would be impressed by your precision and focus.", "You’ve got the strength of a thousand stormtroopers (but with way better aim)!", "Like a true Jedi, you face challenges with courage and wisdom.")

again_list <- c("Even Yoda didn’t get it on the first try. Keep going, young Padawan!", "The Force is strong with you—just focus and try again.", "Every Jedi stumbles before mastering the lightsaber. Give it another go!", "Remember, the greatest pilots still had to learn to fly first.", "Even Han Solo missed a few shots—try again, and you’ll hit the mark.", "No need to go to the Dark Side; persistence will bring you victory!", "The path of the Jedi is filled with lessons. This is just one of them.", "Even Anakin faced failure; it’s how you rise that matters.", "Not even a Sith Lord could conquer every challenge the first time.", "Mistakes are like hyperspace jumps: each one gets you closer to the destination.", "The Rebellion wasn’t won in a day — keep fighting for what’s possible.","Think of this as training with Master Yoda: patience leads to mastery.", "The Force is with you, always, so don’t give up now!", "Just like rebuilding a lightsaber, try again, and you'll get it right.")

random_praise <- sample(praise_list, 1)

random_again <- sample(again_list, 1)

species_count <- starwars |> 
  group_by(species) |> 
  summarize(characters = n()) |> 
  arrange(desc(characters)) |> 
  drop_na()

ggplot(species_count, aes(x = reorder(species, characters), y = characters)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Count of species in Star Wars",
    y = "Number of characters",
    x = ""
  )
```

## JedR Trial No. 4: Plotting

In this JedR Trial, we'll be exploring the [ggplot2](https://ggplot2.tidyverse.org/) skills. Like our previous exercise, we'll be using the data `starwars` in the `tidyverse` packages.

Your humanoid robot editor (J-327D) has asked to _**see**_ how many characters there are for each species in the `starwars` data. They have asked you to make a bar chart from this data.

As you may recall in your training, making a chart usually takes two steps: Preparing the data, then plotting the data.

As a reminder, here is the `starwars` data:

```{webr}
#| edit: false
glimpse(starwars)
```

### Prepare your data

To prepare this data for your plot, you need to:

1. Group by species and count the number of rows. Name the new variable `characters`
1. Arrange the result so the most characters are at the top.
1. Drop any NA values.
1. Save the result of this into a new data frame called `species_count` and then print that out at the end.

```{webr}
#| exercise: ex_1
_____________ <- starwars |>
  ________(_______) |>
  _________(__________ = _()) |>
  _______(____(__________)) |>
  _______()
```

```{webr}
#| exercise: ex_1
#| check: true

if (identical(.result, species_count <- starwars |>
  group_by(species) |>
  summarize(characters = n()) |>
  arrange(desc(characters)) |>
  drop_na())) {
  list(correct = TRUE, message = sample(praise_list, 1))
} else {
  list(correct = FALSE, message = sample(again_list, 1))
}
```

::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 1
Fill in the blanks with functions and variables

``` r
species_count <- starwars |>
  ________(_______) |>
  _________(characters = _()) |>
  _______(desc(characters)) |>
  drop_na()

species_count
```

:::
:::

### Plotting the chart

Now that we have our prepared data into `species_count`, you need to plot your data as a bar chart, with the species with the most characters at the top.

A couple of things that the code checker is persnickety about:

- You should use the geom for a column chart, but the flip it so you can read the species names.
- Don't forget to reorder your bars.
- For the labs, we're looking only for three things:
  - The title should be "Count of species in Star Wars"
  - The axis that has the numbers should be called "Number of characters".
  - The other axis label should be blank or removed.
- Save the results into a new object called `count_chart` and then use `print()` to see the new `count_chart` plot.

```{webr}
#| exercise: ex_2
______(_____________, ___(_ = _______(_______, __________), _ = __________)) +
  ________() +
  __________() +
  ____(
    _____ = "",
    _ = "",
    _ = ""
```

```{webr}
#| exercise: ex_2
#| check: true

if (identical(.result, print(count_chart))) {
  list(correct = TRUE, message = sample(praise_list, 1))
} else {
  list(correct = FALSE, message = sample(again_list, 1))
}
```

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 1
Try building the plot one layer at a time

First, just get the chart to work

```r
ggplot(species_count, ___(x = _______, y = __________)) +
  geom_col()
```

:::
:::

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 2
Then you modify to reorder the bars and flip the coordinates

```r
ggplot(species_count, ___(x = _______(species, characters), y = __________)) +
  geom_col() +
  __________()
```

:::
:::

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 3
Then add your labels

```r
ggplot(species_count, ___(x = _______(species, characters), y = __________)) +
  geom_col() +
  __________() +
  ____(
    _____ = "Count of species in Star Wars",
    y = "Number of characters",
    x = ""
  )
```

:::
:::

Show your completed plot to your JedR Master. "Evil stirs in the galaxy, and the balance trembles. Your training must continue. Step forward, Jedi." [Continue the Fight](/trials/jedr-trial-05-pivot.html)
