---
title: "JedR Trial: Intro"
engine: knitr
format: live-html
webr:
  packages:
    - tidyverse
    - gradethis
  render-df: paged-table
live:
  show-hints: true
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}
{{< include ./_extensions/r-wasm/live/_gradethis.qmd >}}

```{webr}
#| echo: false

gradethis_setup(
  pass.praise = TRUE,
  fail.encourage = TRUE,
)
```


## JedR Trial No. 1: Introduction

Congratulations! You have recently been hired as a **data jedi** for the *Galactic News Hub*, the premiere news organization for the Star Wars Universe. Your first task: apply beginning `tidyverse` skills to learn about the characters in the Star Wars universe you'll be reporting on.

### 1. Previewing our data

For this exercise, we will use the data collection called `starwars`. This data comes with the `tidyverse` package. As you can see below, `starwars` contains some information about Star Wars characters, like their name and height.

Let's learn a bit more about the structure of the `starwars` data and how to conquer these JedR Trials.

This is what it looks like when we load the `tidyverse` library and look at the first few lines in the `starwars` data. Each row of the data is a character within the Star Wars franchise:

```{webr}
#| edit: false
#| message: false
library(tidyverse)

starwars |> head()
```

Within the JedR Trails, you can enter and run code right inside this page. Please make sure to only remove the **underscores** to add your answers. Since the tidyverse was loaded above, all the functions you would normally see in RStudio are available. Once you enter the code, click the blue **Run Code** button to see the results.

The first thing you need to learn is how many rows are in the `starwars` data, along with all the columns and datatypes.

What function would you add to the `starwars` data here to *glimpse* the data and find those answers?

```{webr}
#| label: glimpse
#| exercise: ex_1
_______(starwars)
```

::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}

## Hint 1

`glimpse()` is your jam.
:::
:::

::: {.solution exercise="ex_1"}
::: {.callout-note collapse="false"}

## Solution 1

```{webr}
#| exercise: ex_1
#| solution: true
glimpse(starwars)
```

:::
:::

```{webr}
#| exercise: ex_1
#| check: true
grade_this_code()
```



::: {.callout-tip collapse="true"}

## "How many characters are there in your data? Look at your result above and consider the answer before clicking here to reveal the answer."

There are **87** characters in the `starwars` dataset!
:::

### 2. Focusing on variables

Now that we know how to *glimpse* into our data, let's work on *select*ing specific variables of interest. Let's say the *Galactic News Hub* has asked you to write a story about height differences across different species. What function would you use to *select* only the following variables in `starwars`: `name`, `height`, `homeworld`, and `species`? (Hint: Write your function in that order!)

```{webr}
#| exercise: ex_3
#| label: selecting
starwars |> 
  ______(____, ______, _________, _______)
```

```{webr}
#| exercise: ex_3
#| solution: true
starwars |> select(name, height, homeworld, species)
```


```{webr}
#| exercise: ex_3
#| check: true
grade_this_code()
```

::: {.hint exercise="ex_3"}
::: {.callout-note collapse="false"}
## Hint 1

You might look into the `select()` function, you can [learn about here](https://dplyr.tidyverse.org/reference/select.html).

:::
:::

### 3. Arranging our Data

Now that we have *glimpse*d our data and *select*ed our variables in the `starwars`, let's *arrange* them using by height. What function would we add to our code below to *arrange* our data so that the tallest person is listed at the top? (Hint: since `tidyverse` *arrange*s numbers from the smallest to the greatest number, you may need another function so the information is in *desc*ending order.)

```{webr}
#| exercise: ex_4
starwars |>
  ______(____, ______, _________, _______) |>   
  _______(______ |> ____())
```

```{webr}
#| exercise: ex_4
#| solution: true
starwars |> 
  select(name, height, homeworld, species) |>   
  arrange(height |> desc())
```


```{webr}
#| exercise: ex_4
#| check: true
grade_this_code()
```

::: {.hint exercise="ex_4"}
::: {.callout-note collapse="false"}
## Hint 1

I recommend checking out the `arrange()` function, you can [learn about here](https://dplyr.tidyverse.org/reference/arrange.html). Don't forget to put your result in **desc**ending order.

:::
:::

::: {.callout-tip collapse="true"}
## "If J-327D asked you to write about the tallest being in the galaxy, who would it be? Perhaps a towering Wookiee or a menacing Sith lord... Let’s see!"

The tallest character is **Yarael Poof** with a height of **264 cm**.
:::

Great job! Please inform your JedR Master that you have completed this exercise. You have conquered much, but the next trial calls to you through the Force. Do you dare step forward? [Continue Your Journey](/trials/jedr-trial-02-count.html)