---
title: "JedR Trial: Count"
engine: knitr
format: live-html
webr:
  packages:
    - tidyverse
    - dplyr
    
render-df: paged-table
---

{{< include ./_extensions/r-wasm/live/_knitr.qmd >}}

```{webr}
#| include: FALSE
praise_list <- c("Great job you have done!", "Nice work. You have controlled your fear.", "Wow! The force is with you!", "Great job! Mind tricks don't work on you!", "The Force is strong with you!", "You’ve mastered this task like a true Jedi Knight.", "Your skills rival those of a seasoned Jedi Master.", "The galaxy is lucky to have someone as strong and brave as you.", "The Rebellion couldn’t ask for a better ally.", "You’re the hope the galaxy needs!", "Not even the Death Star could stand in your way.", "Darth Vader would tremble in your presence!", "Even a bounty hunter would be impressed by your precision and focus.", "You’ve got the strength of a thousand stormtroopers (but with way better aim)!", "Like a true Jedi, you face challenges with courage and wisdom.")

again_list <- c("Even Yoda didn’t get it on the first try. Keep going, young Padawan!", "The Force is strong with you—just focus and try again.", "Every Jedi stumbles before mastering the lightsaber. Give it another go!", "Remember, the greatest pilots still had to learn to fly first.", "Even Han Solo missed a few shots—try again, and you’ll hit the mark.", "No need to go to the Dark Side; persistence will bring you victory!", "The path of the Jedi is filled with lessons. This is just one of them.", "Even Anakin faced failure; it’s how you rise that matters.", "Not even a Sith Lord could conquer every challenge the first time.", "Mistakes are like hyperspace jumps: each one gets you closer to the destination.", "The Rebellion wasn’t won in a day — keep fighting for what’s possible.","Think of this as training with Master Yoda: patience leads to mastery.", "The Force is with you, always, so don’t give up now!", "Just like rebuilding a lightsaber, try again, and you'll get it right.")

random_praise <- sample(praise_list, 1)

random_again <- sample(again_list, 1)
```

## JedR Trial No. 2: Summarize by counting

As a **JedR Padawan** of the *Galactic News Hub*, you have been assigned to help with a new story about the demographics of the Star Wars Universe. After pitching a few different topics, your droid editor (J-327D) has green lighted a pitch about species variation. For this article, you have been asked to provide a summary statistic about which species is the most common in the Star Wars universe.

For this task, you will **summarize** and **group** the characters by species. You will then **arrange** the data to identify the most common species of all the Star Wars characters.

### 1. Summarizing

If you recall from our earlier exercise, `starwars` is a dataset with 87 Star Wars characters.

```{webr}
#| edit: false
glimpse(starwars)
```

First, we'll need to *group* the data by species and then *summarize* by counting the *n*umber of rows of each species. (We will tackle the arranging part later.)

How do we do that? What functions would we use? *We insist you name the new variable "characters"!*

```{webr}
#| exercise: ex_1
starwars |>
  ________(_______) |>
  _________(__________ = _())
```

```{webr}
#| exercise: ex_1
#| check: true

if (identical(.result, starwars |>
  group_by(species) |>
  summarize(characters = n()))) {
  list(correct = TRUE, message = sample(praise_list, 1))
} else {
  list(correct = FALSE, message = sample(again_list, 1))
}
```

::: {.hint exercise="ex_1"}
::: {.callout-note collapse="false"}
## Hint 1

Check out the `group_by()` and `summarize()` in [Chapter 4](https://utdata.github.io/rwdir/count-analysis.html#summarize)

:::
:::

### 2. Arrange the results

While the `group_by()` and `summarize()` functions are great for summarizing this information, a [Padawan youngling](https://www.starwars.com/news/what-is-a-padawan) has pointed out that the information is not ordered. 

🙄 Rolling your eyes, you tell them that you know this! We just need to use another function in order to **arrange** this data. To illustrate your point, let's **arrange** this data now.

As a tip, don't forget that we often want to sort the information by **desc**ending order, because journalists are typically interested in the *most* of something.

```{webr}
#| exercise: ex_2
starwars |>
  ________(_______) |>
  _________(__________ = _()) |> 
  _______(__________ |> ____())
```

```{webr}
#| exercise: ex_2
#| check: true

if (identical(.result, starwars |>
  group_by(species) |>
  summarize(characters = n()) |>
  arrange(characters |> desc()))) {
  list(correct = TRUE, message = sample(praise_list, 1))
} else {
  list(correct = FALSE, message = sample(again_list, 1))
}
```

::: {.hint exercise="ex_2"}
::: {.callout-note collapse="false"}
## Hint 1

Check out `arrange()`. You can [learn more here](https://dplyr.tidyverse.org/reference/arrange.html). 

:::
:::

Now that you've **grouped** the data, **summarized** the number of characters of each species, and **arranged** the data (in **desc**ending order), you can finally tell your editor that you've compiled this information!

What species is the most common in Star Wars?

```{webr}
#| exercise: ex_3
"_____"
```

```{webr}
#| exercise: ex_3
#| check: true

if (identical(.result, "Human")) {
  list(correct = TRUE, message = sample(praise_list, 1))
} else {
  list(correct = FALSE, message = sample(again_list, 1))
}
```

::: {.hint exercise="ex_3"}
::: {.callout-note collapse="false"}
## Hint 1

Look at the result of previous code chunk 

:::
:::

Excellent! Please tell your JedR Master that you have completed this trial. "Every trial brings you closer to your destiny. Only those who persist will uncover the truths of the galaxy." [Embrace Your Next Challenge](/trials/jedr-trial-03-sum.html)